apps/mycrud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, Length


# 사용자 신규 작성과 사용자 편집 폼 클래스
class UserForm(FlaskForm):
    # 사용자 폼의 username 속성의 라벨과 벨리데이터를 설정한다
    username = StringField(
        "사용자명",
        validators=[
            DataRequired(message="사용자명은 필수입니다."),
            Length(max=30, message="30문자 이내로 입력해 주세요."),
        ],
    )

    # 사용자폼 email 속성의 라벨과 밸리테이터를 설정한다
    email = StringField(
        "메일 주소",
        validators=[
            DataRequired(message="메일 주소는 필수입니다."),
            Email(message="메일 주소의 형식으로 입력해 주세요."),
        ],
    )

    # 사용자 폼 password 속성의 라벨과 벨리데이터를 설정한다
    password = PasswordField("비밀번호", validators=[DataRequired(message="비밀번호는 필수입니다.")])

    # 사용자폼 submit의 문구를 설정한다
    submit = SubmitField("신규 등록")

apps/mycrud/views.py
from apps.app import db
from apps.crud.models import UserTest
from flask import Blueprint, render_template, redirect, url_for
from apps.mycrud.forms import UserForm


# Blueprint로 crud 앱을 생성한다
mycrud = Blueprint(
    "mycrud",
    __name__,
    template_folder="templates",
    static_folder="static", 
)


# index 엔드포인트를 작성하고 index.html을 반환한다
@mycrud.route("/")
def index():
    return render_template("mycrud/index.html") 

@mycrud.route("/users/new", methods=["GET", "POST"])
def create_user():
    # UserForm을 인스턴스화한다
    form = UserForm()

    # 폼의 값을 벨리데이트한다
    if form.validate_on_submit():
        # 사용자를 작성한다
        user = UserTest(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
        )

        # 사용자를 추가하고 커밋한다
        db.session.add(user)
        db.session.commit()

        # 사용자의 일람 화면으로 리다이렉트한다
        return redirect(url_for("mycrud.users"))
    return render_template("mycrud/create.html", form=form)

@mycrud.route('/users')
def users():
    #사용자의 일람을 취득
    users = UserTest.query.all()
    print(users)
    return render_template('mycrud/index.html',users=users)

@mycrud.route('/user/<user_id>',methods=["POST","GET"])
def edit_user(user_id):
    form = UserForm() #유효성 검사를 위한 객체 생성하기
    user = UserTest.query.filter_by(id=user_id).first() #데이터 얻기
    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("mycrud.users"))
    return render_template('mycrud/edit.html',user=user, form=form)


@mycrud.route("/sql")
def sql():
    db.session.query(UserTest).all()
    # db.session.query(User).first()
    # db.session.query(User).get(2)
    # db.session.query(User).count()
    # User.query.paginate(page=None, per_page=None, error_out=True)
    # db.session.query(User).filter_by(id=2, username="admin").all()
    # db.session.query(User).filter(User.id==2, User.username == "admin").all()
    # db.session.query(User).limit(1).all()
    # db.session.query(User).limit(1).offset(2).all()
    # db.session.query(User).order_by("username").all()
    # db.session.query(User).group_by("username").all()
    # user = User(
    #     username ="jojju",
    #     email = "jojju@naver.com",
    #     password="1234"
    # ) #사용자 모델 객체 생성
    # db.session.add(user) #사용자 추가하기
    # db.session.commit()  #커밋하기
    # user = db.session.query(User).filter_by(id=1).first()
    # user.username = "jojju486"
    # user.email = "jojju486@gmail.com"
    # user.password = "1111"
    # db.session.add(user)
    # db.session.commit()
    # user = db.session.query(User).filter_by(id=1).delete()
    db.session.commit()
    return "콘솔 확인1"

apps/mycrud/templates/mycrud/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <!--title을 상속처에서 구현한다-->
        <title>{% block title %}{% endblock%}</title>
        <link rel="stylesheet" href="{{ url_for('crud.static', filename='style.css')}}" />
    </head>
    <body>
        <!-- content를 상속처에서 구현-->
         {% block content %}{% endblock %}
    </body>
</html>

apps/mycrud/templates/mycrud/create.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <title>사용자 진규 작성</title>        
        <script src="{{ url_for('static', filename='js/script.js') }}"></script>
        <link rel="stylesheet" href="{{url_for('mycrud.static',filename='createStyle.css')}}" />
    </head>
    <body>
        <div id="form-container">
            <div id="form-inner-container">
              <!-- Sign up form -->
                <div id="sign-up-container">
                    <h3>Get Started</h3>
                    <form action="{{url_for('mycrud.create_user')}}" method="POST" novalidate="novalidate">
                        {{form.csrf_token}}

                        {{form.username.label}}
                        {{form.username(placeholder="사용자명")}}
                        {% for error in form.username.errors %}
                        <p><span style="color: red;">{{ error }}</span></p>
                        {% endfor %} 

                        {{form.email.label}} 
                        {{form.email(placeholder="메일주소")}}
                        {% for error in form.username.errors %}
                        <p><span style="color: red;">{{ error }}</span></p>
                        {% endfor %}

                        {{form.password.label}} 
                        {{form.password(placeholder="비밀번호")}}
                        {% for error in form.username.errors %}
                        <p><span style="color: red;">{{ error }}</span></p>
                        {% endfor %}
            
                        <div id="form-controls">                        
                            <button type="submit">Sign Up</button>
                            <button type="button" id="toggleSignIn">Sign In</button>
                        </div>
                        <input type="hidden">
                    </form>
                </div>
              <!-- Sign in form 
              <div id="sign-in-container" class="hide">
                <h3>Welcome Back</h3>
                <form>
                  <label for="username">Username</label>
                  <input type="text" name="username" id="username" placeholder="user@example.com">
      
                  <label for="password">Password</label>
                  <input type="password" name="password" id="password" placeholder="&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;">
      
                  <div id="form-controls">
                    <button type="submit">Sign In</button>
                    <button type="button" id="toggleSignUp">Sign Up</button>
                  </div>
      
                  <input type="checkbox" name="terms" id="terms">
                  <label for="terms">I agree to the <a href="#" class="termsLink">Terms of service</a> and <a href="#" class="termsLink">Privacy Policy</a>.</label>
                </form>
              </div>-->
      
              <!-- Lottie animation -->
              
            </div>
        </div>
    </body>
</html>

apps/mycrud/templates/mycrud/edit.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <title>사용자 정보 수정</title>        
        <script src="{{ url_for('static', filename='js/script.js') }}"></script>
        <link rel="stylesheet" href="{{url_for('mycrud.static',filename='createStyle.css')}}" />
    </head>
    <body>
        <div id="form-container">
            <div id="form-inner-container">
              <!-- Sign up form -->
                <div id="sign-up-container">
                    <h3>사용자 정보 수정</h3>
                    <form action="{{url_for('mycrud.edit_user', user_id=user.id)}}" method="POST" novalidate="novalidate">
                        {{form.csrf_token}}

                        {{form.username.label}}
                        {{form.username(placeholder="사용자명", value=user.username)}}
                        {% for error in form.username.errors %}
                        <span style="color: red;">{{ error }}</span>
                        {% endfor %} 

                        {{form.email.label}} 
                        {{form.email(placeholder="메일주소", value=user.email)}}
                        {% for error in form.username.errors %}
                        <span style="color: red;">{{ error }}</span>
                        {% endfor %}

                        {{form.password.label}} 
                        {{form.password(placeholder="비밀번호")}}
                        {% for error in form.username.errors %}
                        <span style="color: red;">{{ error }}</span>>
                        {% endfor %}

                        <input type="hidden">
            
                        <div id="form-controls">                        
                            <button type="submit">수정</button>
                        </div>                        
                    </form>
                    <form action="{{ url_for('crud.delete_user', user_id=user.id) }}" method="POST">
                        {{ form.csrf_token }}
                        <div id="form-controls">  
                            <button type="submit">삭제</button>
                        </div>                        
                    </form>
                    
                </div>
              <!-- Sign in form 
              <div id="sign-in-container" class="hide">
                <h3>Welcome Back</h3>
                <form>
                  <label for="username">Username</label>
                  <input type="text" name="username" id="username" placeholder="user@example.com">
      
                  <label for="password">Password</label>
                  <input type="password" name="password" id="password" placeholder="&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;">
      
                  <div id="form-controls">
                    <button type="submit">Sign In</button>
                    <button type="button" id="toggleSignUp">Sign Up</button>
                  </div>
      
                  <input type="checkbox" name="terms" id="terms">
                  <label for="terms">I agree to the <a href="#" class="termsLink">Terms of service</a> and <a href="#" class="termsLink">Privacy Policy</a>.</label>
                </form>
              </div>-->
      
              <!-- Lottie animation -->
              
            </div>
        </div>
    </body>
</html>

apps/mycrud/templates/mycrud/index.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <link rel="stylesheet" href="{{url_for('mycrud.static',filename='style.css')}}" />
        <title>mycrud</title>
    </head>

    <body>
        <h2>사용자의 일람</h2>
        
        <table>
            <thead>
            <tr>
                <th>사용자 ID</th>
                <th>사용자명</th>
                <th>메일주소</th>        
            </tr>
            </thead>
            <tbody>
                {% for i in users %} 
                <tr>
                    <td><a href="{{url_for('mycrud.edit_user',user_id=i.id)}}">{{ i.id }}</a></td>
                    <td>{{ i.username }}</td>
                    <td>{{ i.email }}</td>                
                </tr>
                {% endfor %}            
            </tbody>
        </table> 
        <label for="terms"><a href="{{ url_for('mycrud.create_user')}}">사용자 신규 작성</a></label>
    </body>
</html>