apps/crud/models.py
from datetime import datetime
from apps.app import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

# db.Model을 상속한 User 클래스를 작성한다
class User(db.Model, UserMixin):
    # 테이블명을 지정한다
    __tablename__ = "users" 
    
    # 컬럼을 정의한다
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True)
    email = db.Column(db.String, unique=True, index=True)
    password_hash = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)
    print("++++++++++++++++++++++++",id)
    
    # 비밀번호를 세트하기 위한 프로퍼티
    @property
    def password(self):
        raise AttributeError("읽어 들일 수 없음")
    
    # 비밀번호를 세트하기 위한 센터 함수로 해시화한 비밀번호를 세트한다
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)
        
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    def is_duplicate_eamil(self):
        return User.query.filter_by(email=self.email).first() is not None
    
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

        


class UserTest(db.Model, UserMixin):
    # 테이블명을 지정한다
    __tablename__ = "users_test"
    
    # 컬럼을 정의한다
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True)
    email = db.Column(db.String, unique=True, index=True)
    password_hash = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)
    print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",id)
    
    # 비밀번호를 세트하기 위한 프로퍼티
    @property
    def password(self):
        raise AttributeError("읽어 들일 수 없음")
    
    # 비밀번호를 세트하기 위한 센터 함수로 해시화한 비밀번호를 세트한다
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)    
        
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    def is_duplicate_eamil(self):
        return UserTest.query.filter_by(email=self.email).first() is not None
    


    

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, length


# 사용자 신규 작성과 사용자 편집 폼 클래스
class UserForm(FlaskForm):
    # 사용자 폼의 username 속성의 라벨과 벨리데이터를 설정한다
    username = StringField(
        "사용자명",
        validators=[
            DataRequired(message="사용자명은 필수입니다."),
            length(max=30, message="30문자 이내로 입력해 주세요."),
        ],
    )

    # 사용자폼 email 속성의 라벨과 밸리테이터를 설정한다
    email = StringField(
        "메일 주소",
        validators=[
            DataRequired(message="메일 주소는 필수입니다."),
            Email(message="메일 주소의 형식으로 입력해 주세요."),
        ],
    )

    # 사용자 폼 password 속성의 라벨과 벨리데이터를 설정한다
    password = PasswordField("비밀번호", validators=[DataRequired(message="비밀번호는 필수입니다.")])

    # 사용자폼 submit의 문구를 설정한다
    submit = SubmitField("신규 등록")

apps/crud/__init__.py
import apps.crud.models

apps/crud/views.py
from apps.app import db
from apps.crud.models import User
from flask import Blueprint, render_template, redirect, url_for
from apps.crud.forms import UserForm
from flask_login import login_required


# Blueprint로 crud 앱을 생성한다
crud = Blueprint(
    "crud",
    __name__,
    template_folder="templates",
    static_folder="static", 
)

# index 엔드포인트를 작성하고 index.html을 반환한다
@crud.route("/")
@login_required
def index():
    return render_template("crud/index.html") 

@crud.route("/sql")
@login_required
def sql():
    # db.session.query(User).all()
    # db.session.query(User).first()
    # db.session.query(User).get(2)
    # db.session.query(User).count()
    # User.query.paginate(page=None, per_page=None, error_out=True)
    # db.session.query(User).filter_by(id=2, username="admin").all()
    # db.session.query(User).filter(User.id==2, User.username == "admin").all()
    # db.session.query(User).limit(1).all()
    # db.session.query(User).limit(1).offset(2).all()
    # db.session.query(User).order_by("username").all()
    # db.session.query(User).group_by("username").all()
    # user = User(
    #     username ="jojju",
    #     email = "jojju@naver.com",
    #     password="1234"
    # ) #사용자 모델 객체 생성
    # db.session.add(user) #사용자 추가하기
    # db.session.commit()  #커밋하기
    # user = db.session.query(User).filter_by(id=1).first()
    # user.username = "jojju486"
    # user.email = "jojju486@gmail.com"
    # user.password = "1111"
    # db.session.add(user)
    # db.session.commit()
    user = db.session.query(User).filter_by(id=1).delete()
    db.session.commit()
    return "콘솔 확인1"

@crud.route("/users/new", methods=["GET", "POST"])
@login_required
def create_user():
    # UserForm을 인스턴스화한다
    form = UserForm()

    # 폼의 값을 벨리데이트한다
    if form.validate_on_submit():
        # 사용자를 작성한다
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
        )

        # 사용자를 추가하고 커밋한다
        db.session.add(user)
        db.session.commit()

        # 사용자의 일람 화면으로 리다이렉트한다
        return redirect(url_for("crud.users"))
    return render_template("crud/create.html", form=form)

@crud.route('/users')
@login_required
def users():
    #사용자의 일람을 취득
    users = User.query.all()
    print("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
    print(users)
    return render_template('crud/index.html',users=users)
#사용자 편집 화면 엔드포인트
@crud.route('/user/<user_id>',methods=["GET","POST"])
def edit_user(user_id):
    form = UserForm() #객체 생성하기
    user = User.query.filter_by(id=user_id).first() #사용자 취득
    #form으로부터 제출된 사용자를 갱신하여 일람 화면으로 리다이렉트
    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))
    return render_template('crud/edit.html',user=user, form=form)

#사용자 삭제 화면
@crud.route('/user/<user_id>/delete',methods=["POST"])
@login_required
def delete_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('crud.users'))

apps/crud/templates/crud/create.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <title>사용자 진규 작성</title>
    </head>
    <body>
        <h2>사용자 신규 작성</h2>
        <form action="{{url_for('crud.create_user')}}" method="POST" novalidate="novalidate">
            {{form.csrf_token}}
            <p>
                {{form.username.label}} {{form.username(placeholder="사용자명")}}
            </p>
            {% for error in form.username.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %} 
            <p>
                {{form.email.label}} {{form.email(placeholder="메일주소")}}
            </p>
            {% for error in form.username.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %} 
            <p>
                {{form.password.label}} {{form.password(placeholder="비밀번호")}}
            </p>
            {% for error in form.username.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %} 
            <p>{{form.submit()}}</p>
        </form>
    </body>
</html>

apps/crud/templates/crud/edit.html
{% extends "crud/base.html" %}
{%block title%}사용자의 일람{%endblock%}

{%block content%}
<h2>사용자 편집</h2>
<form action="{{ url_for('crud.edit_user', user_id=user.id) }}" method="POST" novalidate="novalidate">
    {{ form.csrf_token }}
    <p>
        {{ form.username.label }} {{ form.username(placeholder="사용자명", value=user.username) }}
    </p>
    {% for error in form.username.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.email.label }} {{ form.email(placeholder="메일 주소", value=user.email) }}
    </p>
    {% for error in form.email.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.password.label }} {{ form.password(placeholder="비밀번호") }}
    </p>
    {% for error in form.password.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p><input type="submit" value="갱신" /></p>
</form>

<form action="{{ url_for('crud.delete_user', user_id=user.id) }}" method="POST">
    {{ form.csrf_token }}
    <input type="submit" value="삭제"> 
</form>
{%endblock%}

apps/crud/templates/crud/index.html
<!--
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <link rel="stylesheet" href="{{url_for('crud.static',filename='style.css')}}" />
        <title>사용자의 일람</title>
    </head>
--> 
{% extends "crud/base.html" %}
{%block title%}사용자의 일람{%endblock%}

{%block content%}
<h2>사용자의 일람</h2>
<a href="{{ url_for('crud.create_user')}}">사용자 신규 작성</a>
<table>
    <tr>
        <th>사용자 ID</th>
        <th>사용자명</th>
        <th>메일주소</th>
    </tr>            
    {% for i in users %}
        <tr>
            <td><a href="{{url_for('crud.edit_user',user_id=i.id)}}">{{ i.id }}</a></td>
            <td>{{ i.username }}</td>
            <td>{{ i.email }}</td>
        </tr>
    {% endfor %}
</table>
{%endblock%}